### ISSUE TITLE
Add qa environment for orangelight

### ISSUE THREAD

**Issue by christinach** [pulibrary/pulbot#38] opened 2020-04-02 22:26 UTC
This will be used to deploy to the orangelight qa server.

**Comment by hackmastera** [comment] 2020-08-18 12:54
@christinach is this a duplicate of #40 or a different server?

**Comment by christinach** [comment] 2020-08-18 15:53
@hackmastera this is for the catalog-qa server. https://github.com/pulibrary/orangelight/pull/2105/files

**Closed** 2020-09-21 15:52 UTC
